debug: true
pomm:
    spore:
        dsn: 'pgsql://sanpi:3.1416@127.0.0.1:5432/spore'

users:
    admin:
        - 'ROLE_ADMIN'
        - '5FZ2Z8QIkA7UTZ4BYkoC+GsReLf569mSKDsfods6LYQ8t+a8EW9oaircfMpmaLbPBh4FOBiiFyLfuZmTSUwzZg=='
